### ISSUE TITLE
Question isn't codegen ignored if we have set lto to true?

### ISSUE THREAD

**Issue by shirshak55** [svenstaro/proxyboi#33]
https://github.com/svenstaro/proxyboi/blob/87f7f2056703524be6ee79b8a728b3880b1cf5cf/Cargo.toml#L20

Question isn't codegen ignored if we have set lto to true?

**Comment by svenstaro** [comment]
Frankly, I don't know. This is interesting though. Do you have some docs on this or some other kind of source?

**Comment by shirshak55** [comment]
I don't know if there is even a docs. I just read a book and saw this project cargo toml file.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8097377/69050410-1e364a00-0a2a-11ea-8b2d-af6a9b5e4ab2.png">

**Comment by svenstaro** [comment]
I had no idea but it should be easy enough to test. I'll try in a bit.

**Comment by shirshak55** [comment]
sure but do benchmark improves if we use lto ?

**Comment by shirshak55** [comment]
i guess we can close this.

**Comment by svenstaro** [comment]
By the way, I eventually tested this and the answer is nope, codegen isn't ignored even with `lto=true`.
