### ISSUE TITLE
[Question] What do opt level z means?

### ISSUE THREAD

**Issue by shirshak55** [svenstaro/proxyboi#35]
https://github.com/svenstaro/proxyboi/blob/87f7f2056703524be6ee79b8a728b3880b1cf5cf/Cargo.toml#L19

I though the value should be 0,1 2 and 3. And C uses level 2 and level 3 should not be used in sensitive system like rockets and satellites?

But this z confused me and cargo docs also don't show me.

**Comment by svenstaro** [comment]
It means to optimize for size but otherwise it's equivalent to `-O2`. See [here](https://rust-embedded.github.io/book/unsorted/speed-vs-size.html#optimize-for-size).

**Comment by shirshak55** [comment]
alright thanks. Its shame we need to go to rust embedded docs just for cargo opt flags :(
