### ISSUE TITLE
Allow sending additional headers to upstream proxy

### ISSUE THREAD

**Issue by svenstaro** [svenstaro/proxyboi#54]
It might be handy to send extra headers to the upstream proxy such as auth. Maybe even add an auth nicety.

**Comment by shirshak55** [comment]
@svenstaro is there any plan. I can PR it for sure but i just don't know how to make it work. Can u please put a light on it?

**Comment by svenstaro** [comment]
This is now implemented in the 0.5.0 release. Sorry it took so long!
